# Generated by Django 5.0.7 on 2024-09-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cards',
            name='cvv',
        ),
        migrations.AddField(
            model_name='cards',
            name='card_number_last4',
            field=models.CharField(default=2002, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
