# Generated by Django 5.0.7 on 2024-09-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0002_remove_cards_cvv_cards_card_number_last4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
