# Generated by Django 5.0.7 on 2024-09-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0005_customuser2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='card_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('blocked', 'blocked')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='card_type',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10, null=True),
        ),
    ]
