# Generated by Django 5.0.7 on 2024-09-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0006_alter_nfccard_card_status_alter_nfccard_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='card_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
