# Generated by Django 5.0.7 on 2024-09-29 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0009_alter_nfccard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfccard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
