# Generated by Django 5.0.7 on 2024-09-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0010_alter_nfccard_user_delete_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='code',
            new_name='verification_code',
        ),
        migrations.RenameField(
            model_name='nfcdata',
            old_name='type',
            new_name='nfc_type',
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='card_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=20),
        ),
    ]
