# Generated by Django 5.0.7 on 2024-09-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0011_rename_code_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verification_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='nfcdata',
            old_name='nfc_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='nfccard',
            name='card_status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('blocked', 'blocked')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
