# Generated by Django 5.0.7 on 2024-10-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0003_customuser_dob'),
        ('restApp', '0012_rename_verification_code_customuser_code_and_more'),
    ]

    operations = [
    ]
