# Generated by Django 5.0.7 on 2024-10-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
