# Generated by Django 5.0.7 on 2024-10-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0002_customuser_phone_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
