# Generated by Django 5.0.7 on 2024-10-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0004_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='req_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
