# Generated by Django 5.0.7 on 2024-10-18 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0005_friendrequest_req_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('external_user', models.CharField(blank=True, max_length=255, null=True)),
                ('operator', models.CharField(max_length=100)),
                ('operator_reference', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('reason', models.TextField(blank=True, null=True)),
                ('reference', models.UUIDField()),
                ('status', models.CharField(choices=[('SUCCESSFUL', 'Successful'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_transation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
