# Generated by Django 5.0.7 on 2024-10-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restApp', '0008_storetransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storetransaction',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restApp.store'),
        ),
    ]
